image: registry.green-rabbit.net:5000/kimata/local_ubuntu:250615_8520de3

stages:
    - build-image
    - pre-test
    - test
    - deploy
    - renovate

build-image:
    stage: build-image

    variables:
        BUILDER: arm_builder

    script:
        - 'TAG="$(date +%y%m%d)_${CI_COMMIT_SHORT_SHA}"'
        
        - 'echo "Building with tag: ${TAG}"'

      
        - export GIT_SSL_NO_VERIFY=1
        - git clone https://gitlab.green-rabbit.net/kimata/bot-config.git
        - mv bot-config/rainfall.yaml ./config.yaml

        - docker buildx create --name ${BUILDER} --use --config /etc/buildkitd.toml
        - docker buildx use ${BUILDER}
        - echo ${CI_REGISTRY_IMAGE}:${TAG}
        - docker buildx build --provenance=false --progress=plain --platform linux/amd64,linux/arm64/v8 --cache-from type=registry,ref=${CI_REGISTRY_IMAGE}:cache --cache-from type=registry,ref=${CI_REGISTRY_IMAGE}:latest --cache-to type=inline --cache-to type=registry,ref=${CI_REGISTRY_IMAGE}:cache,mode=max --build-arg IMAGE_BUILD_DATE=$(date --iso-8601=seconds) --tag ${CI_REGISTRY_IMAGE}:${TAG} --push .
        - docker tag ${CI_REGISTRY_IMAGE}:${TAG} ${CI_REGISTRY_IMAGE}:latest
        - docker push ${CI_REGISTRY_IMAGE}:latest

test-prepare:
    stage: pre-test

    script:
        - apt update
        - apt install --yes build-essential libasound2-dev portaudio19-dev
        - uv sync

    artifacts:
        paths:
            - .venv
            - /root/.cache

    cache:
        key: ${CI_JOB_NAME}
        paths:
            - .venv
            - /root/.cache

test-walk-through:
    stage: test

    dependencies:
        - test-prepare

    script:
        - uv run pytest --timeout=60 --numprocesses=auto --verbosity=1 tests/test_basic.py

deploy:
    stage: deploy

    dependencies: []

    image:
        name: bitnami/kubectl:latest
        entrypoint: ['']

    script:
        - kubectl config get-contexts
        - kubectl config use-context kimata/rainfall-notify:pod-rollout
        - kubectl --insecure-skip-tls-verify=true rollout restart -n bot deployment rainfall-notify-deployment

    rules:
        # NOTE: 自動実行ではデプロイしない
        - if: $CI_PIPELINE_SOURCE == "schedule"
          when: never
        - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
          when: never
        - when: on_success

renovate:
    stage: renovate
    image:
        name: registry.green-rabbit.net:5000/kimata/local_renovate:38

        entrypoint: [""]
    script:
        - renovate --platform gitlab --token ${RENOVATE_TOKEN} --endpoint ${CI_SERVER_URL}/api/v4 ${CI_PROJECT_PATH}
    rules:
        - if: '$CI_COMMIT_BRANCH != "master"'
          when: never
        - if: '$CI_PIPELINE_SOURCE == "schedule"'
        - changes:
            - renovate.json
