liveness:
    file:
        watch: /dev/shm/healthz

influxdb:
    url: http://your-influxdb-server:8086
    org: your-org
    token: your-influxdb-token-here
    bucket: sensor


voice:
    server:
        url: http://your-voice-server:50021

rain_cloud:
    view:
        url: "https://www.jma.go.jp/bosai/nowc/#zoom:13/lat:35.681422/lon:139.762831/colordepth:normal/elements:hrpns&slmcs&slmcs_fcst"
    img:
        url_tmpl: "https://imageflux.tenki.jp/large/static-images/radar/%Y/%m/%d/%H/{:02d}/00/pref-16-large.jpg"

sensor:
    rain_fall:
        hostname: rasp-weather-1
        measure: sensor.rasp

    solar_rad:
        hostname: rasp-weather-1
        measure: sensor.rasp

weather:
    forecast:
        yahoo:
            url: https://weather.yahoo.co.jp/weather/13/4410/13103.html
        tenki:
            url: https://tenki.jp/forecast/3/16/4410/13109/1hour.html

notify:
    line:
        channel:
            access_token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxx

    voice:
        hour:
            start: 8
            end: 21

    footprint:
        voice:
            file: /dev/shm/rainfall.notify.voice
        line:
            file: /dev/shm/rainfall.notify.line

watch:
    interval_sec: 20
